### PR TITLE
WIP: Convert Project to Typescript

### PR DESCRIPTION
**Pull request by BatuhanW**
Unlike `Refactor Typescript` PR, this PR converts project to Typescript, instead of just adding `d.ts` file.

### CODE REVIEW

**Comment by tan-ahmed** [comment]
this project isnt being maintained anymore why don't you just fork and take over ?

**Comment by pawelgrzybek** [comment]
As I mentioned, I will updated it soon. Rewrite to TS is definite part of new release. Stay tuned.

**Comment by pawelgrzybek** [comment]
Is this PR still WIP or ready to review?

**Comment by BatuhanW** [comment]
Still WIP, but I could get some early review @pawelgrzybek

**Comment by sqwk** [comment]
@BatuhanW Regarding #256 : That PR has in fact been fully converted to TS and types are being created automatically through the build process. I think you might have looked at the resulting JS file and not at `src/siema.ts`

**Comment by BatuhanW** [comment]
Since the work is already completed on #256, I'm closing this one.

**Pull request closed without merging**
