### PR TITLE
stopPropagation option added

### PR DESCRIPTION
**Pull request by tatyshev**
#110

### CODE REVIEW

**Comment by tatyshev** [comment]
@pawelgrzybek Do you still maintain this project?

**Comment by pawelgrzybek** [comment]
I still do, just don't have enough time to manage. You don't have to worry I will sort things out during the weekend.

**Comment by matass** [comment]
@tatyshev, shouldn't this option be false by default?

**Comment by tatyshev** [comment]
> @tatyshev, shouldn't this option be false by default?

It would be logical to make this option `false` by default. But I did it on purpose, in order to preserve the backward compatibility with previous versions.

If @pawelgrzybek agrees to make the value `false` by default, I fully agree with this.

**Pull request closed without merging**
