### PR TITLE
New feature: autoplay with configurable delay and pause on mouseover

### PR DESCRIPTION
**Pull request by FNGR2911**
Hi @pawelgrzybek! 
Really looove your lightweight carousel, just great!

Because I needed the feature today, I decided to implement it directly into your siema. So – just if you like, no problem if you don't want implement it or think my code is too ugly ;) – I added an autoplay feature with a configurable delay and an option to pause on hover. Just round about 10 lines.

It's really really basic but it's a start ;)

I also added some info about it to the website and README.

So, I wish you a nice day/night and keep up the great work!
Matthias

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
O wow! Top contributor! Thanks a lot @FNGR2911 man! Let me review everything at some point (weekend perhaps) and if everything is fine I'm happy to merge it with master Siema.

Really thanks and Glad that you like Siema!

👊  👊  👊  👊

**Comment by FNGR2911** [comment]
Glad I can help a little bit @pawelgrzybek 👍  I refactored the PR so it stops the autoplay on touch events too, not just on mouseover!

I hope you can work with it! 👊

**Comment by pawelgrzybek** [comment]
Sorry for delay fellaz! I'm going through all issues and pull requests today and in next few days! Thanks amazing to all of you for amazing input!

**Comment by tomasztomys** [comment]
When can you release new version of Siema with this new feature?

**Comment by pawelgrzybek** [comment]
Hi @FNGR2911 

Just reviewed your code. I really appreciate you pull request. After few tests I decided to keep autoplay functionality as an optional class extension. I will close his PR for now and I will create a CodePen example (credited to you as a solution author) with your implementation.

It seems to be a really nice and clean solution but it is too easy to do it with simple class extension and very few lines of code. Couldn't justify adding it to a class as it's use case is very occasional.

Thanks a lot for contribution again and remember, give my a shout when you are around London! I owe you a beer! 🍻

**Comment by jimblue** [comment]
Hi @pawelgrzybek I can't found the autoplay class nor the exemple...

**Comment by ram-you** [comment]
+1  for a CodePen example.
Thank you.

**Comment by codyogden** [comment]
@ram-you Here's a CodePen with autoplay. https://codepen.io/pawelgrzybek/pen/MbPbLM

**Comment by TrabacchinLuigi** [comment]
hi guys: if you are intrested in autoplay https://github.com/pawelgrzybek/siema/issues/180 i've an example here, also i need to get some attention on the issue :)
P.s. i could not find the class extension too ... and the pr was not merged so ...

**Pull request closed without merging**
