### PR TITLE
Add "overflowHidden" config property

### PR DESCRIPTION
**Pull request by aczekajski**
With current implementation, it is impossible to create a slider with so-called "center mode". Ie. slider with currently chosen slide placed on the center and other slides visible on its sides.

When I do not demand as simple library as Siema is to have this mode built-in, it should at list be possible to achieve with a bit of additional coding outside Siema. Unfortunately it isn't, because of Siema forcing `overflow: hidden` style to the main slider wrapper. This pull request adds a config property called `overflowHidden` with default value set to `true`. This allows the library user to make his own decisions about `overflow` style property.

For example, with code as such:
```html
<div style="overflow: hidden; width: 400px;">
  <div style="overflow: visible; width: 100px; margin: 0 150px;" class="main-carousel-element">
    <!-- slides -->
  </div>
</div>
```
one can achieve effect like that:
image

---
I've also changed a default config merging function a bit. Now it takes from user provided config only those properties that are not undefined, since now providing `undefined` can lead to different bad behaviours of Siema (like throwing `cannot read property "call" of undefined` when you provide `undefined` as `onInit`).

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Hi.

As much as I like the idea and like the centered carousel effect I cannot accept this pull request. Introduced in PR feature can obviously remove `overflow: hidden` but it simply breaks a layout without a parent div that you manually added to your markup in an example above.

This feature is actually a little bit more complicated to achieve with current implementation. It required programatically added div in `int()` method and width to center the carousel to.

I'll review the PR deeply and keep it bookmarked in my mind. Maybe one day I'll add it to the lib, but definitely not to 1.5 yet.

Thanks a lot for your effort and have a great day.

**Comment by aczekajski** [comment]
Of course when you remove this `overflow: hidden` style, user must take control and add it somewhere manually. But that's obvious when you work with sliders, right? Please do look at this example:
https://codepen.io/anon/pen/NXyymd
It works, both with fixed wrapper width and when it is set to 100%.

Readme of Siema states that it has "no styling" because Brad Frost once said "do that shit yourself". So this new options just takes it to its fullest ;) If someone is unable to provide styles that doesn't break layout, he just shouldn't fiddle with option like that.

If you have any scenarios where it breaks Siema or have any further concerns, please tell me. I can help, since this feature is kinda crucial for me ;)

**Comment by pawelgrzybek** [comment]
> But that's obvious when you work with sliders, right?
Nope. This is a wrong aproach. People use libraries to make life easier, not to fight against them.

I totally understand what you are doing in the code and I need to admit that this is looking really great. The point is that only you as an author know what is going on behind, thats what it seems to be very obvious for you to add a bit of css here and there. Majority of users won't won't grasp it as instantly. API should be flexible but it shouldn't give a user an option to break a thing — layout without your styling around a container is simply broken.

Quote from Brad Frost comes from description from his pattern library and the core principale if this one was to give a user something that is working on a first place, and add a nice layout of top of it. Something that your PR is doing is adding something that is broken out of the box and leave it for users to fix it — other way around.

I'm more than happy to develop this feature in collaboration with you because I really like your solution. We just need to make it more "unbreakable". I will review things once again on this weekend and come back to you.

Thanks again for contribution.

**Comment by aczekajski** [comment]
Ok, I got your point. I'll try to think more about a solution that doesn't break a layout. For now I have some quick ideas.

First idea. Since removing `overflow: hidden` breaks things and to fix it one must add an additional wrapper, how about Siema doing it for you? This way you can separate element which width is used for computing slides width, from element with `overflow: hidden`. Again, allowing you to implement center mode. Example usage:
```html
<div class="siema">
  <!-- slides -->
</div>
```
```css
.siema {
  width: 400px;
}
.siema > div {
  width: 100px;
  margin: 0 150px;
}
```
resulting in something like:
```html
<div class="siema" style="overflow: hidden;">
  <div style="overflow: visible;">
    <!-- slides -->
  </div>
</div>
```

Above version, unfortunately makes it impossible to add "fadeout" divs or arrows that appear on the slides in nice way. So, alternatively, you can specify a selector or a node of inner wrapper which user could create by hand to achieve the same effect.
```html
<div class="siema">
  <div class="siema-inner">
    <!-- slides -->
  <div style="overflow: visible;">
</div>
```
```js
new Siema({
  innerWrapper: '.siema-inner', //  or DOM element or true defaulting to first immediate child of '.siema'
});
```
```css
.siema {
  width: 400px;
}
.siema-inner {
  width: 100px;
  margin: 0 150px;
}
```
resulting in the same effect as before (only with additional class).

**Comment by aczekajski** [comment]
Oh, by the way, the two solutions I proposed in previous comment drifted a bit away from original idea. Should I create an issue where we can discuss about what we want to achieve?

**Comment by pawelgrzybek** [comment]
We will discuss them here, no need for issue. I'll review this on this weekend and come back to you with suggestions, solutions, options. Thanks a lot again.

**Comment by AllainPL** [comment]
@pawelgrzybek poke ;)

**Comment by pawelgrzybek** [comment]
Ok.

I think that I found a clean and easy solution for something that you wan't to achieve. Actually this is jus one-liner :)

```js
const mySiema = new Siema({
  onInit() {
    this.selector.style.overflow = 'initial'
  }
});
```

https://codepen.io/pawelgrzybek/pen/EQPXbd

Have a lovely weekend you all 🥑

**Pull request closed without merging**
