### PR TITLE
Feat/callbacks on init, next, prev and drag events

### PR DESCRIPTION
**Pull request by akiokio**
Hello @pawelgrzybek,

First of all slick lib man! I love it 😉

I was using the lib and stumble on the missing callbacks issue to update a progress bar on my little project. So I decided to build myself and here's the result.

I've added the callbacks on the init, next, prev and drag events. The init and drag callbacks can be added via the config object and the next, prev via the click event.

I also added examples on the docs for all the cases. Feel free to merge if you find useful I just want to help. If you want me to change something just tell me.

Thanks,
Akio.

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Boom! Thats the man!

Really amazing and thanks a ton for amazing contribution! The new version of Siema is coming and callbacks are coming with it. RTL mode, `destroy()`, `update()`, `addSlide()`, `removeSlide()` and few other minor improvements. I will take a moment this weekend and review your pull request line by line @akiokio and if not entirely I will marge some parts of it. 

One more time — massive than you! Really appreciate your time and effort. Whenever you around London, let me know because big beer is waiting for you here mate!

Thanks!

🍻🍻🍻

**Comment by akiokio** [comment]
No problem man! 

Just a FYI I added the callback functionality to the goTo function too (and explained on the docs). As my english is not my first language you may find some grammar mistakes.

Will do! You you come to the beautiful Vancouver, BC let me know too. 🍻

**Comment by pawelgrzybek** [comment]
Just had a moment to look at your pull request. Cant thank you enough for your amazing input man!

**Comment by pawelgrzybek** [comment]
Hi @akiokio 

Inspired by your pull request and suggestion by another user I recently released Siema 1.3.0 that introduces basic callbacks on init and on change. It is slightly simplified version of your solution. Thanks a ton for you contribution again.

https://github.com/pawelgrzybek/siema/releases/tag/v.1.3.0

Thanks 🥑

**Pull request closed without merging**
