### PR TITLE
"infinite looping" enhance the loop, by make the first element connected to the last element and the last element with first element

### PR DESCRIPTION
**Pull request by ahabeb**
enhance the loop, by make the first element connected to the last element and the last element with first element
by clone the first element and last element, and do zero transition from cloned elements

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Thank you for sending PR. I will review it this weekend. Amazing idea — I was thinking about implement this kind of "infinite looping".

Thanks amazing and have an amazing weekend!

**Comment by pawelgrzybek** [comment]
OK. I gave it a quick test without looking at the code yet. Just created a quick CodePen example to preview a final effect.

https://codepen.io/pawelgrzybek/pen/JNmzoW

Unfortunately it doesn't work and breaks so many functionality. What was your intention to create, we can combine powers and add this functionality but I cannot merge this code in a current form. I will do a detailed code review later on.

**Comment by ahabeb** [comment]
Hey, I looked to your example
you didn't pass loop with true value, please try it with loop true.
https://codepen.io/ahabeb/pen/aWRgPV

I think i missed one thing incase loop was false .. i will check that

**Comment by pawelgrzybek** [comment]
Need some time to review it again then :) Thanks for great action mate!

**Comment by steveooo9** [comment]
@pawelgrzybek Funny, I just stumbled upon your great plugin and currently only found this one thing that I disliked. But this infinite scrolling would be a great thing in Siema!

I also like that everything is so minimalistic and therefore pretty stable. Keep up the good work and hopefully we have a new stable thing (after using slick for some years with some quirks -.-)

**Comment by bravecow** [comment]
Didn't review, but cool feature 👍

**Comment by gilazr** [comment]
Hi!
Great feature :)
@pawelgrzybek , will this be merged / implemented in the next releases?

thanks

**Comment by digitalkaoz** [comment]
@ahabeb great work! @pawelgrzybek a merge would be lovely :) i tried this PR and it works like a charm :-*

**Comment by RiceCrisp** [comment]
Looking forward to that merge :)

**Comment by RiceCrisp** [comment]
I'm noticing a bug when perPage is set to anything greater than 1.

**Comment by digitalkaoz** [comment]
@pawelgrzybek why you close this without any comment.

as you stated here: https://github.com/pawelgrzybek/siema/issues/60#issuecomment-303616007 its high on your priority list...

**Comment by pawelgrzybek** [comment]
Github automatically closed it because I removed a remote branch with all upcoming features in 1.5.0. You can be assured that this feature will land very soon tho :) The implementation is going to be similar to this one suggested on this pull request with tiny changes and fixes. Sorry for misleading notifications guys.

**Comment by digitalkaoz** [comment]
@pawelgrzybek :-* awesome!

**Comment by tomerf8** [comment]
Tested it locally and its great! nice work!

**Comment by pawelgrzybek** [comment]
Hi.

Feature that you requested has been merged with master branch and it is ready to use.

https://codepen.io/pawelgrzybek/pen/zwOrKN

Thanks again for using Siema 👋

**Pull request closed without merging**
