### PR TITLE
Support infinite loop

### PR DESCRIPTION
**Pull request by chenliangde**

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Hi.

Thank you for your effort and your contribution to Siema. Unfortunately this feature is much more complicated that you cover in your PR. I cannot merge it with master as it broke the whole script on a first second when I tried your PR.

By the war, this feature is coming to Siema in a next big update 1.5.

Thanks again and have a nice day 🥑

screenflow

**Comment by chenliangde** [comment]
Thanks for trying it. Is there a ETA of 1.5?

Regards
Chen

**Comment by pawelgrzybek** [comment]
Hi.

I't is really high on my priority list to deliver it ASAP, but I need some time to work on few features that require a bit of logic. I think I will drop 1,5 before and of February. There is lots of cool stuff to come — rtl support, wrapArround, autoHeight, unit tests etc...

Thanks 🥑

**Comment by chenliangde** [comment]
Thanks, looking forward to it

**Comment by pawelgrzybek** [comment]
Hi.

Feature that you requested has been merged with master branch and it i ready to use.

https://codepen.io/pawelgrzybek/pen/zwOrKN

Thanks again for using Siema 👋

**Comment by chenliangde** [comment]
Thank you for the update

**Comment by rosnaib11** [comment]
Hi it seems the infinite loop not working anymore in your example?

**Pull request closed without merging**
