### PR TITLE
Resolve problem with PWA standards (passive events)

### PR DESCRIPTION
**Pull request by piecioshka**
Hi @pawelgrzybek !

I've just resolve problem which I was saw during audit my conference page https://confrontjs.com

More details: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Wait a sec. As far as I know, not all DOM events take a passive option. Need to confirm that and come back here at some point.

**Comment by ODudek** [comment]
@pawelgrzybek I can help you, quotation from link that @piecioshka added:

> Add the passive flag to all of the event listeners that Lighthouse has identified. In general, add the passive flag to every wheel, mousewheel, touchstart, and touchmove event listener that does not call preventDefault().

**Comment by pawelgrzybek** [comment]
Point taken ! Thanks pals!

**Review by keletsomolefe — APPROVED** [review]

**Comment by tomrutgers** [comment]
Would love to see this merged!

**Comment by VivienGiraud** [comment]
Any ETA for a merge?

**Review by svyatoff — APPROVED** [review]

**Comment by panoply** [comment]
Just to note,  passive `true` with `touchmove` is better off being set to `false` to prevent content shifts.

**Comment by sokyran** [comment]
Any updates on the merge? 🙏

**Review by pawelgrzybek — APPROVED** [review]

**Pull request merged**
