### PR TITLE
#10 adding rtl support

### PR DESCRIPTION
**Pull request by aboodz**
all you need is to add `dir="rtl"` on any parent element of siema carouel (e.g. on `<body>`)
```
<div class="siema" dir="rtl">
  <div>Hi, I'm slide 1</div>
  <div>Hi, I'm slide 2</div>
  <div>Hi, I'm slide 3</div>
  <div>Hi, I'm slide 4</div>
</div>
```

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
Hi.

Thanks for your contribution. I need a bit of time to review this PR.

Have a great day 🥑

**Comment by aboodz** [comment]
Take your time. 
If you found any issue please inform me. Honestly, I did not test my code much.

**Comment by pawelgrzybek** [comment]
Hi.

Thanks a ton for your effort and amazing contribution. I reviewed the PR and I have a few reasons why I  cannot merge it with a master branch unfortunately.

1. The `getComputedStyle()` method isn't needed here. It is very performance heavy function and more importantly `rtl` should be configurable. In case someone would like to use a Siema inside an `iframe`.
2. Example.html isn't needed.
3. There is incomplete webpack tweak that seems to be broken that is not a subject of a PR.
4. Adding class to siema breaks one if its core rules - style free.
5. It reverts back passive events that I remover intentionally on one of the previous fixes.
6. It breaks current browser support by changing layout model to flexbox.
7. It adds some padding feature that is not related with a subject of a PR.
8. Last commit confused me the most.

Please try to keep your PR as small as possible, as focused on one subject as possible, without adding unnecessary bells and whistles.

I will keep your solution in mind because I'm in process of implementing rtl feature to next big relase 1.5.

Thanks again for your solution and have a great day 🥑

**Comment by aboodz** [comment]
Good morning,

Opps, I am really sorry for the confusion I created. Only the first commit is related to rtl issue. Other changes were not meant to be pushed to this repository (We have an internal git repository). By mistake I pushed them to Github. In the last commit I have reverted everything back to the first commit. 

Anyways, my rtl solution is simple, I only multiply `translate3d` value by -1 when div direction is rtl. I can create the pull request again if you want.  Now it is true that `getComputedStyle()` is heavy. I think it is not an issue if it is only called once during initialization. If you do want to change it, you can read direction value from document itself. Something like this could do `document.dir || document.body. 

Please ignore flexbox and other changes. There were part of an experiment using flexbox.
Best of luck

**Comment by pawelgrzybek** [comment]
Thanks for coming back to me. I have an implementation of this feature ready and it will be merges with 1.5 very soon.

Thanks for your contribution again and have a great day 🥑

**Comment by pawelgrzybek** [comment]
Finally! Feature is merged with master and ready to use guys. Enjoy :)

https://codepen.io/pawelgrzybek/pen/XZNEgd

**Pull request closed without merging**
